name: Triggered Action

on:
  repository_dispatch:
    types:
      - trigger-event
env:
  GITHUB_BASE_URL: https://github.com/kaleidpixel
  PACKAGE_NAME: imgopt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Create derived env variables
        run: |
          echo "GITHUB_REPOSITORY_URL=${{ env.GITHUB_BASE_URL }}/${{ env.PACKAGE_NAME }}" >> $GITHUB_ENV
          echo "FORMULA_RUBY=Formula/${{ env.PACKAGE_NAME }}.rb" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get redirected URL from latest release
        id: get-url
        run: |
          URL=$(curl -sI ${{ env.GITHUB_REPOSITORY_URL }}/releases/latest | grep "location" | awk '{print $2}' | tr -d '\r')
          VERSION=$(echo $URL | grep -o "v[0-9.]\+")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download and read SHA256
        id: get-sha256
        run: |
          SHA256=$(curl -sL ${{ env.GITHUB_REPOSITORY_URL }}/releases/download/${{ env.VERSION }}/${{ env.PACKAGE_NAME }}-x64-win.zip.sha256)
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: cat ${{ env.FORMULA_RUBY }}
        run: cat ${{ env.FORMULA_RUBY }}

      - name: Update ${{ env.FORMULA_RUBY }}
        run: |
          sed -i "s|${{ env.GITHUB_REPOSITORY_URL }}/releases/download/v[0-9.]*/${{ env.PACKAGE_NAME }}.phar$|${{ env.GITHUB_REPOSITORY_URL }}/releases/download/${{ env.VERSION }}/${{ env.PACKAGE_NAME }}.phar|g" ${{ env.FORMULA_RUBY }}
          sed -i "sds|sha256 \"[0-9A-Za-z]*\"$|sha256 \"${{ env.SHA256 }}\"|g" ${{ env.FORMULA_RUBY }}

      - name: cat ${{ env.FORMULA_RUBY }}
        run: cat ${{ env.FORMULA_RUBY }}

      - name: Commit and push if changed
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ env.FORMULA_RUBY }}
          git commit -m "Update ${{ env.FORMULA_RUBY }} with new version ${{ env.VERSION }}" || echo "No changes to commit"
          git push
